-- AC02:

-- UTILIZANDO O BANCO DE DADOS PEDIDOS, EXECUTAR OS EXERCÍCIOS ABAIXO:

--1. SELECIONAR OS DEPENDENTES QUE TERMINEM O NOME COM ALGUMA VOGAL
SELECT *
FROM TB_DEPENDENTE
WHERE NOME
LIKE '%[aeiou]'

--2. RETORNAR A QUANTIDADE DE FORNECEDORES POR CIDADE, QUE CONTENHAM "LTDA" OU "COM" OU "IND" EM SEU NOME
SELECT COUNT(*) AS QTD_FORNECEDOR, CIDADE
FROM TB_FORNECEDOR
WHERE NOME
LIKE '%LTDA'
  OR NOME LIKE '%COM'
  OR NOME LIKE '%IND'
GROUP BY CIDADE

--3. CONFIGURAR O CEP DOS FORNECEDORES PARA RETORNAR NO FORMATO: "CEP: NN.NNN-NNN"
SELECT (SUBSTRING (CEP,1,2) + '.'
+ SUBSTRING (CEP,3,3) + '-'
+ SUBSTRING (CEP,6,3)) AS CEP_FORNECEDOR
FROM TB_FORNECEDOR
WHERE LEN(CEP) = 8

--4. RETORNAR A SOMA DE SALÁRIOS POR DEPARTAMENTO E POR CARGO
SELECT SUM(SALARIO) AS TOTAL_SALARIO, COD_DEPTO, COD_CARGO
FROM TB_EMPREGADO
GROUP BY COD_DEPTO, COD_CARGO

--5. DETERMINAR QUAL O CLIENTE MAIS ANTIGO E QUAL O CLIENTE O MAIS NOVO
SELECT MIN(DATA_CAD)	AS CLIENTE_MAIS_ANTIGO
FROM TB_CLIENTE

SELECT *
FROM TB_CLIENTE
WHERE DATA_CAD = '1997-02-06'

SELECT MAX(DATA_CAD)	AS CLIENTE_MAIS_NOVO
FROM TB_CLIENTE

SELECT *
FROM TB_CLIENTE
WHERE DATA_CAD = '1997-10-22'

--6. DETERMINAR A SOMA DE VENDAS POR ANO E POR MES (AAAA/MM) NA TABELA DE PEDIDOS
SELECT COUNT(*) AS QTD_VENDAS, YEAR(DATA_EMISSAO) AS ANO, MONTH(DATA_EMISSAO) AS MÊS
FROM TB_PEDIDO
GROUP BY YEAR(DATA_EMISSAO) ,MONTH(DATA_EMISSAO)
ORDER BY MONTH(DATA_EMISSAO)

--7. RETORNAR O TOP 3 VENDEDORES QUE POSSUEM MAIOR MÉDIA DE VENDAS
SELECT TOP 3
  AVG(VLR_TOTAL) AS MEDIA_VENDEDOR, CODVEN
FROM TB_PEDIDO
GROUP BY CODVEN
ORDER BY SUM(VLR_TOTAL)

--8. INSERIR O TOTAL DE VENDAS QUE O VENDEDOR FEZ POR CLIENTE (OBJETIVO: SABER QUAL VENDEDOR MAIS FIDELIZA CLIENTES)
SELECT COUNT(CODCLI)
AS QTD_VENDA,
CODVEN AS VENDEDOR,
CODCLI AS CLIENTE
FROM TB_PEDIDO
GROUP BY CODVEN, CODCLI
